from economy import Economy

economy = Economy(
    id="BASIC_TROPIC",
    numeric_id=4,
    # as of May 2015 the following cargos must have fixed positions if used by an economy:
    # passengers: 0, mail: 2, goods 5, food 11
    # keep the rest of the cargos alphabetised
    # bump the min. compatible version if this list changes
    cargos=[
        "passengers",
        "acetic_acid",
        "mail",
        "alcohol",
        "biomass",
        "goods",
        "building_materials",
        "chemicals",
        "clay",
        "cleaning_agents",
        "coal",
        "food",  # has to be out of order for compatibility
        "coke",
        "copper",
        "copper_concentrate",
        "copper_ore",
        "edible_oil",
        "engineering_supplies",
        "explosives",
        "farm_supplies",
        "fertiliser",
        "fish",
        "flour",
        "food_additives",
        "fruits",
        "glass",
        "grain",
        "iron_ore",
        "limestone",
        "livestock",
        "logs",
        "meat",
        "milk",
        "nitrates",
        "oil",
        "oil_seeds",
        "packaging",
        "paints_and_coatings",
        "petrol",
        "phosphate",
        "phosphoric_acid",
        "pig_iron",
        "plant_fibres",
        "plastics",
        "quicklime",
        "rare_metals",
        "recyclables",
        "rubber",
        "salt",
        "sand",
        "scrap_metal",
        "slag",
        "soda_ash",
        "steel",
        "steel_sections",
        "sugarcane",
        "sugar",
        "sulphur",
        "sulphuric_acid",
        "textiles",
        "timber",
        "tyres",
        "vehicle_parts",
        "vehicles",

    ],
    # as of April 2021 this cargoflow graph is really as optimised as can be
    # the main driver is preventing ugly appearance of the edges that converge on food, most of the layout is arranged around preventing that
    cargoflow_graph_tuning={}
)
